# Generated by Django 5.1.1 on 2024-11-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrocompra',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
